---
  output: html_fragment
---

```{r setup, echo = FALSE}

knitr::opts_chunk$set(message = FALSE, warning = FALSE, echo = FALSE)

```

```{r}
library(soilDB)
library(ggplot2)
library(scales)
library(DT)
library(plotly)
library(forcats)
library(RColorBrewer)

ps <- parseWebReport("https://nasis.sc.egov.usda.gov/NasisReportsWebSite/limsreport.aspx?report_name=get_projectstaff_from_LIMS", args = list(p_mlrassoarea = paste0(isolate(input$psso), "%"), p_fy = paste0(isolate(input$pfy))))

ps$username[is.na(ps$username)] <- "Unknown"

ps$region <- gsub("-...$", "", ps$mlrassoarea)

ps <- subset(ps, projecttypename != "ES")
ps <- subset(ps, projecttypename != "PES")

# ps$sums <- aggregate(ps$acre_goal, by = list(Category=ps$acre_goal), FUN = sum)

len1 = length(unique(ps$mlrassoarea))
len2 = length(unique(ps$region))

psag <- aggregate(ps$acre_goal, by = list(mlrassoarea = ps$mlrassoarea, region = ps$region), FUN = sum)
psags <- psag[order(psag$x, decreasing = TRUE),]

# test$region <- as.numeric(test$region)

# test$region <- test$mlrassoarea

# test2 <- test[test$region == "10",]
# test3 <- test[test$region == "11",]
# 
# test4 <- rbind(test2, test3)
#   

# pl1 <- ggplot(ps) +
#   geom_col(aes(y = acre_goal, x = username, group = mlrassoarea, fill = region)) +
#   facet_grid(as.numeric(region) + mlrassoarea ~ ., scales = "free") +
#   coord_flip() +
#   scale_y_continuous(labels = scales::comma)
# 
# pl1
```

```{r, fig.height = len1, out.width = '75%'}
pl3 <- ggplot(ps) +
  geom_col(aes(y = acre_goal, x = username, group = mlrassoarea, fill = region)) +
  facet_wrap(~ as.numeric(region) + mlrassoarea, scales = "free_y", ncol = 2, dir = "v") +
  coord_flip() +
  scale_y_continuous(labels = scales::comma) +
  labs(y = "Goal (in Acres)", x = "User Name")

pl3
```

```{r, fig.height = len2, out.width = '75%'}
pl2 <- ggplot(psags) +
  geom_col(aes(y = x, x = region, group = x, fill = (mlrassoarea)), position = position_stack()) +
  # facet_wrap(~ as.numeric(region), scales = "free", ncol = 2, dir = "v") +
  coord_flip() +
  scale_y_continuous(labels = scales::comma) +
  labs(y = "Goal (in Acres)", x = "Region") +
  # guides(fill = guide_legend(ncol=3))
  geom_text(aes(x = region, y = x,label = mlrassoarea, angle = 90), position = position_stack(vjust= .5), size = 3) +
  guides(fill = FALSE)

pl2

```

```{r}
pldt <- DT::datatable(ps)

pldt

```